### ISSUE TITLE
Fix score rule

### ISSUE THREAD

**Issue by pa3ng** [pa3ng/thorhousebot#1]
@josephsjliu 

Some indentation errors.

Also, some keywords in the actions aren't a thing. Will try to get the docs published for flottbot so you know which ones to use.

score.yaml
```yaml
# metadata
name: scorekeeper
active: true # activate rule

# trigger & arguments
respond: Ian
args: 
	- score #amount to give/take
	- reason #reason for score update

# actions
actions: 
	-name: scoreboard http request
	 type: POST
	 url: https://slack.com/api/chat.command
	 token: ${SLACK_TOKEN}
	 channel: #testing
	 command: /scoreboard
	 text: "give @beh beh ${score} ${reason}"
	 response: "Giving beh beh ${score} for ${reason}"

# response
format_output: "${response}"


start_message_thread: false # start a thread with the response
direct_message_only: false # allow messaging inside channels

#help
help_text: Ian # help/usage text for the echo rule
include_in_help: true # see help_text in help message
```
